# Site settings
author: Luis Concepcion
title: Data Science Blog
header-img: img/home-bg.png
email: lconcepcion@hotmail.com
copyright_name: Luis Concepcion
description: > # this means to ignore newlines until "baseurl:"
  Luis Concepcion's Data Science Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lrconcepcion

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
